server:
  port: 8086

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/powerup_restaurants
    username: root
    password: ''

  application:
    name: restaurant-service

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
appDescription: "Pragma Powerup"
appVersion: "1.0.0"
