server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/powerup_users
    username: root
    password: ''

  application:
    name: user-service

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
appDescription: "Pragma Powerup"
appVersion: "1.0.0"